---
- name: Setting up DEVASC VM
  hosts: localhost
  connection: local
  become: true
  
  # vars_prompt:
  #   - name: existing_user
  #     prompt: "Enter your existing username"
  #     private: no
  #   - name: existing_user_pass
  #     prompt: "Enter your existing password"

  vars:
    - hostname: labvm
    - existing_user: devasc 
    - existing_user_pass: Cisco123!
    - ciscouser: devasc 
    - ciscopass: Cisco123!
    - ansible_become_password: "{{existing_user_pass}}"
    - user_home: "/home/devasc"
    - desktop_path: "{{ user_home }}/Desktop"
    - ubuntuversion: focal
    - user_groups:
      - wireshark
      - docker
    # - app_dir: /opt/sample-python-api
    # - repo_url: "https://github.com/nikolayg/sample-python-api.git"
    # - service_name: sample-python-api
    # - python_exec: /usr/bin/python3


  
  tasks:
    - name: Setting the hostname to {{hostname}}
      hostname:
        name: "{{hostname}}"

    - name: Update /etc/hosts for new hostname
      lineinfile:
        path: /etc/hosts
        regexp: '^(127\.0\.1\.1\s+).*'
        line: "127.0.1.1   {{ hostname }}"

    - name: Create neccesary groups
      group:
        name: "{{item}}"
        state: present
      with_items: "{{ user_groups }}"



    - name: Allow devasc  to run sudo without password
      copy:
        dest: "/etc/sudoers.d/devasc" 
        content: "devasc  ALL=(ALL) NOPASSWD:ALL"
        owner: root
        group: root
        mode: '0440'


    - name: Add apt key for docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add apt key for vscode
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ubuntuversion}} stable
        filename: docker
        state: present
      notify:
        - Apt update

    - name: Add vscode repository
      apt_repository:
        repo: deb https://packages.microsoft.com/repos/code stable main
        filename: vscode
        state: present
      notify:
        - Apt update

    - name: Remove nosnap.pref so we can install snapd
      file:
        path: /etc/apt/preferences.d/nosnap.pref
        state: absent

    - name: Update ubuntu packages [please wait]
      apt:
        name: "*"
        state: latest
        cache_valid_time: 3600
        update_cache: yes

    - name: Install main software packages [please wait]
      apt:
        name:
          - ansible
          - apt-transport-https
          - ca-certificates
          - containerd.io
          - curl
          - dconf-cli
          - docker-ce
          - docker-ce-cli
          - docker-compose-plugin
          - git
          - gnupg
          - htop
          - inetutils-traceroute
          - lsb-release
          - mc
          - neofetch
          - net-tools
          - open-vm-tools
          - open-vm-tools-desktop
          - openssh-server
          - python3
          - python3-pip
          - python3-venv
          - snapd
          - snapd-xdg-open
          - software-properties-common
          - sqlitebrowser
          - sshpass
          - stunnel4
          - tcpdump
          - tcptrace
          - tcptraceroute
          - telnet
          - ubuntu-mate-desktop
          - vim
          - vmfs-tools
          - wget
          - wireshark

        state: latest
        cache_valid_time: 3600
        update_cache: yes

    - name: Install snap software packages
      snap:
        name: 
          - drawio
          - postman
          - chromium
          - code
        state: present
    
    - name: Add vscode extension(s) for devasc
      become: false
      become_user: devasc
      command: code --install-extension ms-python.python

    - name: Install Python packages
      become: false
      become_user: devasc
      pip:
        name:
          - faker
          - flask
          - flask_restplus
          - ncclient
          - netmiko
          - pep8
          - pip
          - pipenv
          - pyang
          - pyats[full]
          - pylint
          - pyotp
          - requests
          - tabulate
          - webexteamssdk
          - werkzeug
        state: latest
        extra_args: --break-system-packages

    # Install mate desktop environment and set it as default
    - name: Install MATE Desktop Environment
      apt:
        name: ubuntu-mate-desktop
        state: present
        cache_valid_time: 3600
        update_cache: yes
      notify: Restart GDM

    - name: Set MATE as default session
      lineinfile:
        path: /etc/gdm3/custom.conf
        regexp: '^#?DefaultSession='
        line: 'DefaultSession=mate.desktop'
        insertafter: '[daemon]'
      notify: Restart GDM

    # Create desktop shortcuts
    - name: Create desktop shortcut for Firefox
      copy:
        dest: "/home/devasc/Desktop/firefox.desktop"
        content: |
          [Desktop Entry]
          Name=Firefox
          Exec=firefox
          Icon=firefox
          Type=Application
          Terminal=false
        mode: '0755'
    
    - name: Ensure Desktop folder exists
      file:
        path: "{{ desktop_path }}"
        state: directory
        owner: devasc
        group: devasc
        mode: '0755'

    - name: Shortcut for Home Folder
      copy:
        dest: "{{ desktop_path }}/home.desktop"
        content: |
          [Desktop Entry]
          Name=Home
          Exec=nautilus {{ user_home }}
          Icon=user-home
          Type=Application
          Terminal=false
        mode: '0755'
        owner: devasc
        group: devasc

    - name: Shortcut for Labs Folder
      copy:
        dest: "{{ desktop_path }}/labs.desktop"
        content: |
          [Desktop Entry]
          Name=Labs
          Icon=folder
          Type=Link
          URL=/home/devasc/labs
          Icon=user-bookmarks
        mode: '0755'
        owner: devasc
        group: devasc

    - name: Shortcut for Terminal
      copy:
        dest: "{{ desktop_path }}/terminal.desktop"
        content: |
          [Desktop Entry]
          Name=Terminal
          Exec=gnome-terminal
          Icon=utilities-terminal
          Type=Application
          Terminal=false
        mode: '0755'
        owner: devasc
        group: devasc

    - name: Shortcut for VSCode
      copy:
        dest: "{{ desktop_path }}/vscode.desktop"
        content: |
          [Desktop Entry]
          Name=Visual Studio Code
          Exec=/snap/bin/code
          Icon=code
          Type=Application
          Terminal=false
        mode: '0755'
        owner: devasc
        group: devasc

    - name: Shortcut for Chromium
      copy:
        s
        dest: "{{ desktop_path }}/chromium.desktop"
        content: |
          [Desktop Entry]
          Name=Chromium
          Exec=/snap/bin/chromium-browser
          Icon=chromium-browser
          Type=Application
          Terminal=false
        mode: '0755'
        owner: devasc
        group: devasc

    
    # Setup to prevent screen from going to sleep
    - name: Disable GNOME idle timeout
      command: >
        sudo -u devasc dbus-launch gsettings set org.gnome.desktop.session idle-delay 0

    - name: Disable GNOME power sleep on AC
      command: >
        sudo -u devasc dbus-launch gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing'

    - name: Disable GNOME power sleep on battery
      command: >
        sudo -u devasc dbus-launch gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type 'nothing'

    - name: Update systemd logind.conf to ignore lid and idle
      blockinfile:
        path: /etc/systemd/logind.conf
        block: |
          [Login]
          HandleLidSwitch=ignore
          IdleAction=ignore
      notify: Restart systemd-logind


        

  handlers:
    - name: Restart systemd-logind
      service:
        name: systemd-logind
        state: restarted
    - name: Apt update
      apt:
        update_cache: true
    - name: Restart GDM
      service:
        name: gdm3
        state: restarted
