---
- name: Setting up DEVASC VM
  hosts: localhost
  connection: local
  become: true
  
  # vars_prompt:
  #   - name: existing_user
  #     prompt: "Enter your existing username"
  #     private: no
  #   - name: existing_user_pass
  #     prompt: "Enter your existing password"

  vars:
    - hostname: labvm
    - existing_user: devasc 
    - existing_user_pass: Cisco123!
    - ciscouser: devasc 
    - ciscopass: Cisco123!
    - ansible_become_password: "{{existing_user_pass}}"
    - user_home: "/home/devasc"
    - desktop_path: "{{ user_home }}/Desktop"
    - ubuntuversion: focal
    - user_groups:
      - wireshark
      - docker
  
  tasks:
    - name: Disable idle delay (set to 0)
      command: gsettings set org.gnome.desktop.session idle-delay 0

    - name: Setting the hostname to {{hostname}}
      hostname:
        name: "{{hostname}}"

    - name: Update /etc/hosts for new hostname
      lineinfile:
        path: /etc/hosts
        regexp: '^(127\.0\.1\.1\s+).*'
        line: "127.0.1.1   {{ hostname }}"

    - name: Create neccesary groups
      group:
        name: "{{item}}"
        state: present
      with_items: "{{ user_groups }}"

    - name: Allow devasc  to run sudo without password
      copy:
        dest: "/etc/sudoers.d/devasc" 
        content: "devasc  ALL=(ALL) NOPASSWD:ALL"
        owner: root
        group: root
        mode: '0440'

    - name: Add apt key for docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add apt key for vscode
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ubuntuversion}} stable
        filename: docker
        state: present
      notify:
        - Apt update

    - name: Remove nosnap.pref so we can install snapd
      file:
        path: /etc/apt/preferences.d/nosnap.pref
        state: absent

    - name: Install main software packages [please wait]
      apt:
        name:
          - ansible
          - apt-transport-https
          - ca-certificates
          - containerd.io
          - curl
          - dconf-cli
          - docker-ce
          - docker-ce-cli
          - docker-compose-plugin
          - git
          - gnupg
          - htop
          - inetutils-traceroute
          - lsb-release
          - mc
          - neofetch
          - net-tools
          - open-vm-tools
          - open-vm-tools-desktop
          - openssh-server
          - python3
          - python3-pip
          - python3-venv
          - snapd
          - snapd-xdg-open
          - software-properties-common
          - sqlitebrowser
          - sshpass
          - stunnel4
          - tcpdump
          - tcptrace
          - tcptraceroute
          - telnet
          - ubuntu-mate-desktop
          - vim
          - vmfs-tools
          - wget
          - wireshark

        state: latest
        cache_valid_time: 3600
        update_cache: yes

    - name: Update ubuntu packages [please wait]
      apt:
        name: "*"
        state: latest
        cache_valid_time: 3600
        update_cache: yes

    - name: Install snap software packages
      snap:
        name: 
          - drawio
          - postman
          - chromium
        state: present
    
    - name: Install VSCode classic
      snap:
        name: code
        classic: yes
        state: present
    
    - name: Add vscode extension(s) for devasc
      become: false
      become_user: devasc
      command: code --install-extension ms-python.python
    # Configure VS Code to disable Copilot
    - name: Ensure VS Code settings directory exists
      file:
        path: "{{ user_home }}/.config/Code/User"
        state: directory
        mode: '0755'

    - name: Ensure VS Code settings.json exists with Copilot disabled
      copy:
        dest: "{{ user_home }}/.config/Code/User/settings.json"
        content: |
          {
            "github.copilot.agent.enabled": false,
            "github.copilot.chat.enabled": false,
            "github.copilot.inlineSuggest.enable": false,
            "workbench.experimental.enableCopilot": false,
            "extensions.autoUpdate": false,
            "extensions.ignoreRecommendations": true,
            "chat.disableAIFeatures": true
          }
        mode: '0644'

    # Install packet tracer .deb package
    - name: Download packet tracer .deb file
      get_url:
        url: "https://www.netacad.com/authoring-resources/courses/ff9e491c-49be-4734-803e-a79e6e83dab1/c3636211-1ce6-4f92-8a22-ccddf902dd72/en-US/assets/PacketTracer822_amd64_signed_en-US_35234a27-3127-49bc-91ce-2926af76f07a.deb"
        dest: "{{ user_home }}/PacketTracer.deb"
        mode: '0644'

    - name: Install .deb package
      apt:
        deb: "{{ user_home }}/PacketTracer.deb"
        state: present


    - name: Install Python packages
      become: false
      become_user: devasc
      pip:
        name:
          - faker
          - flask
          - flask_restplus
          - ncclient
          - netmiko
          - pep8
          - pip
          - pipenv
          - pyang
          - pyats[full]
          - pylint
          - pyotp
          - requests
          - tabulate
          - webexteamssdk
          - werkzeug
        state: latest
        extra_args: --break-system-packages

    # Install mate desktop environment and set it as default
    - name: Install MATE Desktop Environment
      apt:
        name: ubuntu-mate-desktop
        state: present
        cache_valid_time: 3600
        update_cache: yes
      notify: Restart GDM

    - name: Set MATE as default session
      lineinfile:
        path: /etc/gdm3/custom.conf
        regexp: '^#?DefaultSession='
        line: 'DefaultSession=mate.desktop'
        insertafter: '[daemon]'
      notify: Restart GDM

    # Create desktop shortcuts
    - name: Create desktop shortcut for Firefox
      copy:
        dest: "/home/devasc/Desktop/firefox.desktop"
        content: |
          [Desktop Entry]
          Name=Firefox
          Exec=firefox
          Icon=firefox
          Type=Application
          Terminal=false
        mode: '0755'
    
    - name: Ensure Desktop folder exists
      file:
        path: "{{ desktop_path }}"
        state: directory
        owner: devasc
        group: devasc
        mode: '0755'

    - name: Ensure lab folder exists
      file:
        path: "{{ desktop_path }}/labs"
        state: directory
        owner: devasc
        group: devasc
        mode: '0755'

    - name: Shortcut for Labs Folder
      copy:
        dest: "{{ desktop_path }}/labs.desktop"
        content: |
          [Desktop Entry]
          Name=Labs
          Icon=folder
          Type=Link
          URL=/home/devasc/labs
          Icon=user-bookmarks
        mode: '0755'
        owner: devasc
        group: devasc

    - name: Shortcut for Terminal
      copy:
        dest: "{{ desktop_path }}/terminal.desktop"
        content: |
          [Desktop Entry]
          Name=Terminal
          Exec=gnome-terminal
          Icon=utilities-terminal
          Type=Application
          Terminal=false
        mode: '0755'
        owner: devasc
        group: devasc

    - name: Shortcut for VSCode
      copy:
        dest: "{{ desktop_path }}/vscode.desktop"
        content: |
          [Desktop Entry]
          Name=Visual Studio Code
          Exec=/snap/bin/code
          Icon=/snap/code/current/meta/gui/vscode.png
          Type=Application
          Terminal=false
        mode: '0755'
        owner: devasc
        group: devasc

    - name: Shortcut for postman
      copy:
        dest: "{{ desktop_path }}/postman.desktop"
        content: |
          [Desktop Entry]
          Name=Postman
          Exec=/snap/bin/postman
          Icon=/snap/postman/current/usr/share/postman/icons/icon_128x128.png
          Type=Application
          Terminal=false
        mode: '0755'
        owner: devasc
        group: devasc

    - name: draw.io Shortcut
      copy:
        dest: "{{ desktop_path }}/drawio.desktop"
        content: |
          [Desktop Entry]
          Name=draw.io
          Exec=/snap/bin/drawio
          Icon=/snap/drawio/current/meta/gui/icon.png
          Type=Application
          Terminal=false
        mode: '0755'
        owner: devasc
        group: devasc

    - name: Shortcut for Chromium
      copy:
        dest: "{{ desktop_path }}/chromium.desktop"
        content: |
          [Desktop Entry]
          Name=Chromium
          Exec=/snap/bin/chromium
          Icon=/snap/chromium/current/chromium.png
          Type=Application
          Terminal=false
        mode: '0755'
        owner: devasc
        group: devasc

    
    # Setup to prevent screen from going to sleep
    - name: Disable GNOME idle timeout
      command: >
        sudo -u devasc dbus-launch gsettings set org.gnome.desktop.session idle-delay 0

    - name: Disable GNOME power sleep on AC
      command: >
        sudo -u devasc dbus-launch gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing'

    - name: Disable GNOME power sleep on battery
      command: >
        sudo -u devasc dbus-launch gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type 'nothing'

    - name: Update systemd logind.conf to ignore lid and idle
      blockinfile:
        path: /etc/systemd/logind.conf
        block: |
          [Login]
          HandleLidSwitch=ignore
          IdleAction=ignore
      notify: Restart systemd-logind

    # Setup IP addresses
    - name: Write netplan configuration
      copy:
        dest: /etc/netplan/01-netcfg.yaml
        content: |
          network:
            version: 2
            renderer: networkd
            ethernets:
              eth:
                match:
                  name: e*
                dhcp4: yes
            bridges:
              dummy0:
                dhcp4: no
                dhcp6: no
                accept-ra: no
                interfaces: []
                addresses:
                  - 192.0.2.1/32 # library.demo.local
                  - 192.0.2.2/32 # pt-controller.demo.local
                  - 192.0.2.3/32 # TBD
                  - 192.0.2.4/32 # TBD
                  - 192.0.2.5/32 # TBD
        owner: root
        group: root
        mode: '0644'
      notify: Apply netplan
    
    - name: Ensure host entries exist
      lineinfile:
        path: /etc/hosts
        create: yes
        line: "{{ item }}"
      loop:
        - "192.0.2.1 library.demo.local"
        - "192.0.2.2 pt-controller.demo.local"


    # Setup API-SIMULATOR service
    - name: Ensure required packages for PPA are installed
      apt:
        name: software-properties-common
        state: present
        update_cache: yes

    - name: Add Deadsnakes PPA
      apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Python 3.8 and venv tools
      apt:
        name:
          - python3.8
          - python3.8-venv
          - python3.8-dev
        state: present

    - name: Copy API-SIMULATOR directory
      command: cp -r "{{ user_home }}/devasc-vm-setup/API-SIMULATOR" /opt/
        
    - name: Create Python virtual environment for API-SIMULATOR
      command: python3.8 -m venv /opt/API-SIMULATOR/venv
      args:
        creates: /opt/API-SIMULATOR/venv/bin/activate

    - name: Install API-SIMULATOR requirements
      pip:
        requirements: /opt/API-SIMULATOR/requirements.txt
        virtualenv: /opt/API-SIMULATOR/venv
    
    - name: Create systemd service file for API-SIMULATOR
      copy:
        dest: /etc/systemd/system/api-simulator.service
        content: |
          [Unit]
          Description=API Simulator Flask App
          After=network.target

          [Service]
          Type=simple
          ExecStart=/opt/API-SIMULATOR/start-API-SIMULATOR.sh
          WorkingDirectory=/opt/API-SIMULATOR
          Restart=always
          User=www-data
          Environment="PATH=/usr/local/bin:/usr/bin"
          Environment="PYTHONUNBUFFERED=1"

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: '0644'
      notify:
        - Reload systemd
        - Restart API-SIMULATOR

    - name: Enable API-SIMULATOR service
      systemd:
        name: api-simulator.service
        enabled: yes
        state: started


    - name: Ensure managed policies directory exists
      file:
        path: /etc/chromium/policies/managed
        state: directory
        mode: '0755'

    - name: Set homepage policy
      copy:
        dest: /etc/chromium/policies/managed/homepage.json
        content: |
          {
            "HomepageLocation": "http://library.demo.local",
            "HomepageIsNewTabPage": false,
            "RestoreOnStartup": 4,
            "RestoreOnStartupURLs": ["http://library.demo.local"]
          }
        owner: root
        group: root
        mode: '0644'

    # Setup lab folder
    - name: Copy labs directory
      copy:
        src: "{{ user_home }}/devasc-vm-setup/labs"
        dest: "{{ user_home }}"

  handlers:
    - name: Restart systemd-logind
      service:
        name: systemd-logind
        state: restarted
    - name: Apt update
      apt:
        update_cache: true
    - name: Restart GDM
      service:
        name: gdm3
        state: restarted
    - name: Reload systemd
      command: systemctl daemon-reload

    - name: Restart API-SIMULATOR
      systemd:
        name: api-simulator.service
        state: restarted
    - name: Apply netplan
      command: netplan apply