---
- name: Configure DEVASC VM
  hosts: localhost
  connection: local
  become: true
  vars_files:
    - group_vars/all.yml
  roles:
    - common
    - users
    - packages
    - desktop
    - netplan
    - api_simulator